-- 1. Profiles Table (User Metadata)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  user_type TEXT DEFAULT 'employee', -- 'admin', 'employer', 'employee'
  points INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Shops Table (Job Postings)
CREATE TABLE shops (
  id TEXT PRIMARY KEY, -- Using existing IDs from JSON
  name TEXT NOT NULL,
  region TEXT,
  phone TEXT,
  kakao TEXT,
  telegram TEXT,
  pay TEXT,
  work_type TEXT,
  url TEXT,
  site TEXT,
  is_premium BOOLEAN DEFAULT FALSE,
  is_verified BOOLEAN DEFAULT FALSE,
  is_placeholder BOOLEAN DEFAULT FALSE,
  tier TEXT, -- 'grand', 'premium', 'deluxe', 'special', 'urgent', 'recommended'
  title TEXT,
  pay_type TEXT,
  ad_no INTEGER,
  options JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Community Posts Table
CREATE TABLE community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  is_hot BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Community Comments Table
CREATE TABLE community_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES community_posts(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_comments ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Public read for now)
CREATE POLICY "Public read for shops" ON shops FOR SELECT USING (true);
CREATE POLICY "Public read for posts" ON community_posts FOR SELECT USING (true);
CREATE POLICY "Public read for comments" ON community_comments FOR SELECT USING (true);
CREATE POLICY "Public read for profiles" ON profiles FOR SELECT USING (true);

-- Admin policies can be added later as needed
