-- 1. Resumes Table (이력서 정보)
CREATE TABLE IF NOT EXISTS resumes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  age TEXT,
  region TEXT,
  intro TEXT,
  tags TEXT[], -- ['야간', '서빙'] 등
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Point Logs Table (포인트 적립/사용 내역)
CREATE TABLE IF NOT EXISTS point_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL, -- 적립은 (+), 사용은 (-)
  reason TEXT NOT NULL, -- '회원가입', '이력서 등록', '게시글 작성', '쇼핑몰 쿠폰 교환' 등
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE point_logs ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Explicitly cast to TEXT to avoid UUID vs TEXT comparison errors)
DO $$
BEGIN
    -- Resumes Policy
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'resumes' AND policyname = 'Users can manage their own resumes'
    ) THEN
        CREATE POLICY "Users can manage their own resumes" ON resumes
          FOR ALL USING (auth.uid()::text = user_id::text);
    END IF;

    -- Point Logs Policy
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'point_logs' AND policyname = 'Users can view their own point logs'
    ) THEN
        CREATE POLICY "Users can view their own point logs" ON point_logs
          FOR SELECT USING (auth.uid()::text = user_id::text);
    END IF;
END
$$;

-- 5. Trigger for updated_at (resumes)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_resumes_updated_at ON resumes;
CREATE TRIGGER update_resumes_updated_at
    BEFORE UPDATE ON resumes
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
