-- 1. Profiles Table (User Metadata)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  full_name TEXT,
  nickname TEXT,
  role TEXT DEFAULT 'individual', -- 'admin', 'corporate', 'individual'
  is_admin BOOLEAN DEFAULT FALSE,  -- [New] 어드민 여부
  points INTEGER DEFAULT 0,         -- [New] 코코 포인트
  
  -- [Business Verification Fields]
  business_name TEXT,               -- 상호명
  business_number TEXT,             -- 사업자등록번호 (10자리 숫자만)
  business_type TEXT,               -- 업종
  business_address TEXT,            -- 사업장 주소
  business_address_detail TEXT,     -- 상세 주소
  business_file_url TEXT,           -- 사업자등록증 파일 URL
  business_verify_status TEXT DEFAULT 'none', -- none, pending, approved, rejected
  business_verify_requested_at TIMESTAMP WITH TIME ZONE,
  
  -- [Staff Contact Fields]
  manager_phone TEXT,               -- 담당자 연락처
  manager_kakao TEXT,               -- 담당자 카카오톡 ID
  manager_line TEXT,                -- 담당자 라인 ID
  manager_telegram TEXT,            -- 담당자 텔레그램 ID
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Point Logs Table (Autonomous Logging)
CREATE TABLE point_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  reason TEXT NOT NULL, -- JOIN, ATTENDANCE_CHECK, ADMIN_GRANT 등
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Shops Table (Job Postings)
CREATE TABLE shops (
  id TEXT PRIMARY KEY, -- Using existing IDs from JSON
  name TEXT NOT NULL,
  region TEXT,
  phone TEXT,
  kakao TEXT,
  telegram TEXT,
  pay TEXT,
  work_type TEXT,
  url TEXT,
  site TEXT,
  is_premium BOOLEAN DEFAULT FALSE,
  is_verified BOOLEAN DEFAULT FALSE,
  is_placeholder BOOLEAN DEFAULT FALSE,
  tier TEXT, -- 'grand', 'premium', 'deluxe', 'special', 'urgent', 'recommended'
  title TEXT,
  pay_type TEXT,
  ad_no INTEGER,
  options JSONB DEFAULT '{}'::jsonb,
  status TEXT DEFAULT 'PENDING_REVIEW', -- [New] 공고 상태 관리
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Community Posts Table
CREATE TABLE community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  is_hot BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Community Comments Table
CREATE TABLE community_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES community_posts(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Public read for now)
-- Strict Security Policies (Privacy & Integrity)
CREATE POLICY "Public read for shops" ON shops FOR SELECT USING (status = 'published');
CREATE POLICY "Public read for posts" ON community_posts FOR SELECT USING (true);
CREATE POLICY "Public read for comments" ON community_comments FOR SELECT USING (true);

-- [CRITICAL] profiles: Only owner or admin can read sensitive data
CREATE POLICY "Profiles read policy" ON profiles FOR SELECT USING (
    (auth.uid() = id) OR 
    (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true))
);

-- 5. Payments Table (Unified Finance Tracking)
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  shop_id TEXT, -- Relation to shops.id (optional as some payments like SOS/Points don't have shop_id)
  amount INTEGER NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending', -- pending, completed, rejected
  type TEXT DEFAULT 'AD',        -- AD, JUMP, SOS, OPTION
  method TEXT,                    -- card, bank, points
  metadata JSONB DEFAULT '{}'::jsonb, -- Store snapshot info (e.g. ad period, SOS count)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Auto-Join Points Trigger (The "Total Command" Core)
-- 신규 가입 시 profiles 생성 및 100P 지급 자동화
CREATE OR REPLACE FUNCTION public.handle_new_user_setup()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, nickname, role, points)
  VALUES (
    new.id,
    split_part(new.email, '@', 1),
    new.raw_user_meta_data->>'full_name',
    COALESCE(new.raw_user_meta_data->>'nickname', new.raw_user_meta_data->>'full_name'),
    COALESCE(new.raw_user_meta_data->>'role', 'individual'),
    100 -- 가입 축하 포인트
  );

  INSERT INTO public.point_logs (user_id, amount, reason, note)
  VALUES (new.id, 100, 'JOIN', '[System] 신규 가입 축하 보너스');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_setup();
