export interface Post {
    id: number;
    category: string;
    title: string;
    content: string;
    author: string;
    time: string;
    likes: number;
    comments: number;
    views?: number;
    isHot?: boolean;
}

export const CATEGORIES = [
    { id: 'all', name: '전체' },
    { id: 'nightlife', name: '밤 문화 Talk' },
    { id: 'talk', name: '언니들의 수다(썰)' },
    { id: 'partner', name: '같이일할단짝' },
    { id: 'market', name: '중고거래' },
    { id: 'legal', name: '무료법률상담' },
    { id: 'beauty', name: '뷰티·패션·이벤트' },
    { id: 'lounge', name: '프리미엄 라운지' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];

export const MOCK_POSTS: Post[] = [
    {
        id: 40,
        category: '프리미엄 라운지',
        title: '언니들 블랙리스트 공유할게요 (필독)',
        content: '요즘 이상한 손님들이 너무 많네요. 제가 직접 겪은 블랙리스트 명단 공유합니다. 다들 조심하세요! 특히 00시에 나타나는 30대 중반 키 큰 남자는 진짜 요주의 인물입니다.',
        author: '정보통',
        time: '5분 전',
        likes: 245,
        comments: 6,
        isHot: true,
    },
    {
        id: 41,
        category: '뷰티·패션·이벤트',
        title: '이번에 새로 나온 샤넬 립스틱 발색 후기',
        content: '샤넬 신상 발라봤는데 역시 하늘 아래 같은 핑크는 없네요.. 이번 시즌 컬러 진짜 대박이에요. 촉촉하면서도 지속력 좋아서 데일리로 딱입니다.',
        author: '뷰티퀸',
        time: '12분 전',
        likes: 156,
        comments: 4,
        isHot: true,
    },
    {
        id: 42,
        category: '프리미엄 라운지',
        title: '오픈 3일차 수입 공개합니다...',
        content: '걱정 많이 했는데 생각보다 잘 벌리네요. 저처럼 고민하는 언니들 위해 용기 내서 올립니다! 첫날에는 좀 헤맸는데 둘째날부터 요령이 생기니까 수입이 확 늘었어요.',
        author: '뉴비언니',
        time: '20분 전',
        likes: 312,
        comments: 8,
        isHot: true,
    },
    {
        id: 50,
        category: '언니들의 수다(썰)',
        title: '회피형 남친이랑 3년 사귀고 환승 당한 썰.. 제가 바보였나요?',
        content: '진짜 손이 떨려서 글 써요. 3년 동안 싸움만 나면 동굴 들어가고 잠수 타던 남친.. 고쳐 보겠다고 옆에서 온갖 정성 다 쏟았는데 결국 한 달 만에 다른 여자 인스타에 럽스타그램 올라오네요. 회피형은 정말 고쳐 쓰는 거 아닌가 봐요.',
        author: '눈물나네',
        time: '25분 전',
        likes: 420,
        comments: 15,
        isHot: true,
    },
    {
        id: 51,
        category: '언니들의 수다(썰)',
        title: '예비 시댁에서 자꾸 혼수를 폰으로 보내는데 이거 어쩌죠?',
        content: '결혼 한 달 남았는데 예비 시어머니가 자꾸 링크를 보내요. 소파부터 가전까지 본인 취향인 것만.. 심지어 가격대도 만만치 않은데 저희 형편은 생각도 안 하시나 봐요. 남친은 효자라 말도 못 하고.. 파혼 각인가요?',
        author: '답답해',
        time: '40분 전',
        likes: 380,
        comments: 12,
        isHot: true,
    },
    {
        id: 52,
        category: '언니들의 수다(썰)',
        title: '어제 손님으로 온 전남친이랑 마주쳤습니다 (심장 터질뻔)',
        content: '알바하는데 문 열고 들어오는 사람이 너무 낯익어서 봤더니 2년 전에 헤어진 전남친.. 옆에는 예쁜 여자분 데리고 왔더라고요. 저랑 눈 마주쳤는데 모르는 척하더라고요. 화장실 가서 한참 울다 나왔네요.',
        author: '멘탈바사삭',
        time: '1시간 전',
        likes: 510,
        comments: 22,
        isHot: true,
    },
    {
        id: 53,
        category: '언니들의 수다(썰)',
        title: '30대 언니들아, 연애할 때 이거 꼭 보세요 (결혼 조건)',
        content: '나이 먹고 연애하려니까 감정보다는 조건부터 보게 되네요. 근데 제가 깨달은 건 돈보다 인성이 1순위라는 거예요. 아무리 돈 많아도 말 예쁘게 안 하는 남자는 결국 상처만 주더라고요. 언니들은 뭘 보시나요?',
        author: '경험담',
        time: '2시간 전',
        likes: 210,
        comments: 9,
    },
    {
        id: 54,
        category: '언니들의 수다(썰)',
        title: '여우 같은 여우 짓? 제가 한 번 해봤습니다 ㅋㅋ',
        content: '평범한 제가 이번에 맘에 드는 남자 꼬시려고 여우 짓 좀 해봤는데 대성공했어요! 역시 남자는 칭찬과 리액션에 약하네요. 혹시 궁금한 언니들 있으면 댓글 달아주세요 공유할게요!',
        author: '성공적',
        time: '3시간 전',
        likes: 180,
        comments: 35,
        isHot: true,
    },
    {
        id: 1,
        category: '밤 문화 Talk',
        title: '오늘 퇴근길 노을 보셨나요? 진짜 힐링..✨',
        content: '요즘 일하느라 너무 바빴는데 잠깐 고개 들어보니 하늘이 너무 예쁘더라고요. 언니들도 오늘 하루 고생 많으셨어요!',
        author: '익명123',
        time: '10분 전',
        likes: 12,
        comments: 2,
    },
    {
        id: 17,
        category: '프리미엄 라운지',
        title: '멘탈 관리하는 나만의 루틴 공유 🧘‍♀️',
        content: '명상이랑 가벼운 독서가 큰 도움이 되네요. 바쁜 일상 속에서도 마음의 여유를 찾는 팁들입니다.',
        author: '퀸즈',
        time: '1시간 전',
        likes: 89,
        comments: 5,
    },
    {
        id: 6,
        category: '밤 문화 Talk',
        title: '동네 맛집 추천 좀 해주세요 (강남역 근처)',
        content: '오늘 친구랑 만나기로 했는데 조용하고 분위기 좋은 곳 있을까요? 파스타나 일식 선호합니다!',
        author: '배고픈다람쥐',
        time: '4시간 전',
        likes: 9,
        comments: 3,
    },
    {
        id: 18,
        category: '밤 문화 Talk',
        title: '멀티비타민 이거 진짜 물건이네요 ㅋㅋ',
        content: '직업 특성상 피로를 달고 사는데.. 이거 먹고 나서부터 아침이 달라요. 내돈내산 찐후기입니다.',
        author: '비타민짱',
        time: '45분 전',
        likes: 15,
        comments: 4,
    },
    {
        id: 33,
        category: '프리미엄 라운지',
        title: '남사친이 자꾸 선 넘는데, 이거 썸인가요? 🙄',
        content: '맨날 먼저 연락 오고, 술 마시자고 하는데 막상 만나면 그냥 친구 같아요. 언니들이 보기엔 어떤가요?',
        author: '고민녀',
        time: '30분 전',
        likes: 15,
        comments: 5,
    },
    {
        id: 80,
        category: '언니들의 수다(썰)',
        title: '전남친 결혼식 가서 축의금 1,000원 내고 뷔페 3그릇 먹고 온 썰 ㅋㅋ',
        content: '어차피 모르는 척할 거 뻔해서 아주 화려하게 꾸미고 갔어요. 신부보다 제가 더 예쁘다는 소리 들으니까 기분 최고더라고요. 식권 받아서 랍스터까지 야무지게 챙겨 먹고 왔습니다. 언니들, 최고의 복수는 내가 더 잘 사는 모습을 보여주는 거예요!',
        author: '복수여왕',
        time: '1시간 전',
        likes: 1540,
        comments: 120,
        isHot: true,
    },
    {
        id: 81,
        category: '언니들의 수다(썰)',
        title: '첫 출근했는데 사장님이 제 인스타 보더니 홍보 모델 하라네요 ㅠ',
        content: '사무직인 줄 알고 갔는데 제 인스타 팔로워 보더니 갑자기 업체 홍보 영상 찍어보라고.. 페이는 더 준다는데 이거 계속해야 할까요? 제가 하는 일이 바뀔까 봐 걱정돼요.',
        author: '사회초년생',
        time: '2시간 전',
        likes: 420,
        comments: 45,
        isHot: true,
    },
    {
        id: 82,
        category: '프리미엄 라운지',
        title: '언니들, 20대에 1억 모으기.. 진짜 가능한 거였어? (인증)',
        content: '잠 안 자고 투잡 뛰고 재테크 공부해서 드디어 앞자리 바꿨어요! 처음엔 막막했는데 절약하는 법이랑 투자 포트폴리오 짜니까 눈에 보이더라고요. 비결 궁금한 언니들 댓글 주면 제 루틴 공유할게요!',
        author: '자산가언니',
        time: '3시간 전',
        likes: 2100,
        comments: 310,
        isHot: true,
    },
    {
        id: 83,
        category: '언니들의 수다(썰)',
        title: '남사친이 자꾸 새벽에 전화해서 전여친 욕하는데.. 손절각이죠?',
        content: '자기는 피해자인 척하면서 전여친만 나쁜X 만드는데, 듣고 있으면 제가 다 기가 빨려요. 처음엔 위로해 줬는데 매일 이러니까 이제는 전화벨만 울려도 짜증 나네요. 그냥 조용히 차단할까요?',
        author: '기빨려요',
        time: '4시간 전',
        likes: 180,
        comments: 65,
    },
    {
        id: 84,
        category: '언니들의 수다(썰)',
        title: '어제 클럽에서 만난 남자가 알고 보니 울 회사 거래처 팀장님 ㅋㅋㅋ',
        content: '어쩐지 어디서 많이 본 얼굴이다 싶었는데.. 오늘 미팅에서 마주치고 서로 눈 피하느라 죽는 줄 알았네요 ㅋㅋ 그분도 당황한 게 눈에 보이는데 앞으로 어떡하죠?',
        author: '민망한만남',
        time: '5시간 전',
        likes: 890,
        comments: 82,
        isHot: true,
    },
    {
        id: 85,
        category: '언니들의 수다(썰)',
        title: '소개팅에서 밥 먹고 2차로 편의점 가서 캔맥주 마시자는 남자.. 어때요?',
        content: '분위기 좋은 술집 가자니까 자기 아는 단골 노상 맛집이 있다면서 편의점 앞 테이블로 데려가네요.. 날씨도 추운데 이게 맞는 건지.. 제가 너무 까다로운 건가요?',
        author: '황당그잡채',
        time: '6시간 전',
        likes: 315,
        comments: 156,
        isHot: true,
    },
    {
        id: 86,
        category: '언니들의 수다(썰)',
        title: '남친의 은밀한 취미.. 이거 이해해줘야 하나요? (고민)',
        content: '남친이 피규어 수집하는 건 알았는데, 그 가격이 제가 생각한 것보다 훨씬 높더라고요. 이번 달 월급의 절반을 썼다는데 앞으로 결혼 자금은 언제 모으려고 이러는지 모르겠어요. 취존 해줘야 할까요?',
        author: '취미전쟁',
        time: '8시간 전',
        likes: 120,
        comments: 94,
    },
    {
        id: 87,
        category: '언니들의 수다(썰)',
        title: '30대 솔로 언니들, 이번 명절 대피소 어디로 가세요? ✈️',
        content: '잔소리 듣기 싫어서 저는 혼자 호캉스 예약했어요! 차라리 돈 좀 쓰고 마음 편한 게 최고네요. 언니들은 명절에 어떻게 시간을 보내시는지 궁금해요!',
        author: '행복한싱글',
        time: '12시간 전',
        likes: 540,
        comments: 73,
        isHot: true,
    },
    {
        id: 88,
        category: '프리미엄 라운지',
        title: '성공한 언니가 말해주는 "부자 남친" 만나는 법 🤫',
        content: '단순히 예쁜 것보다 중요한 건 본인의 가치를 높이는 거예요. 그들이 모이는 장소, 나누는 대화 주제를 공부하세요. 제가 직접 겪은 상위 1% 남자들의 특징과 공략법 공유합니다.',
        author: '성공학개론',
        time: '15시간 전',
        likes: 4500,
        comments: 520,
        isHot: true,
    },
    {
        id: 89,
        category: '언니들의 수다(썰)',
        title: '알바 면접 갔는데 사장님이 제 인스타 팔로워 수부터 물어보네요 ㅋ',
        content: '일 잘하는 건 안 보고 파급력이 얼마나 되는지만 궁금해하는 것 같아서 기분 나빠서 그냥 나왔어요. 요즘은 알바도 셀럽 아니면 못 하나 봐요? 황당해서 글 써봅니다.',
        author: '알바지망생',
        time: '20시간 전',
        likes: 210,
        comments: 38,
    },
    {
        id: 35,
        category: '프리미엄 라운지',
        title: '회피형 인간하고 연애하는 언니들 필독 (탈출기) ✂️',
        content: '싸우기만 하면 잠수 타는 전남친 때문에 1년을 고생했네요. 결국 헤어지고 나니까 속이 다 시원해요. 회피형은 고쳐 쓰는 거 아니라는 말, 뼈저리게 느낍니다.',
        author: '탈출성공',
        time: '2시간 전',
        likes: 88,
        comments: 7,
        isHot: true,
    },
];

export const MOCK_COMMENTS = [
    { id: 101, postId: 1, author: '공감봇', content: '맞아요.. 오늘 노을 진짜 미쳤더라구요 ㅠㅠ', time: '5분 전' },
    { id: 102, postId: 1, author: '언니야', content: '고생 많으셨어요! 푹 쉬세요 ㅎㅎ', time: '2분 전' },
    { id: 103, postId: 50, author: '사이다원해', content: '회피형은 절대 사람 안 돼요. 잘 탈출하셨어요!', time: '10분 전' },
    { id: 104, postId: 50, author: '경험자1', content: '저도 똑같은 일 겪었는데 지금 너무 행복해요. 힘내세요!', time: '5분 전' },
    { id: 105, postId: 51, author: '냉철하게', content: '그거 시작이에요. 파혼이 답입니다 진짜로.', time: '15분 전' },
    { id: 106, postId: 52, author: '눈물쓱', content: '아이고.. 맘고생 심하시겠어요. 맛있는 거 먹고 털어버려요!', time: '30분 전' },
];
