export interface Post {
    id: number;
    category: string;
    title: string;
    content: string;
    author: string;
    time: string;
    likes: number;
    comments: number;
    views?: number;
    isHot?: boolean;
}

export const CATEGORIES = [
    { id: 'all', name: '전체' },
    { id: 'nightlife', name: '밤 문화 Talk' },
    { id: 'partner', name: '같이일할단짝' },
    { id: 'market', name: '중고거래' },
    { id: 'legal', name: '무료법률상담' },
    { id: 'beauty', name: '뷰티·패션·이벤트' },
    { id: 'lounge', name: '프리미엄 라운지' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];

export const MOCK_POSTS: Post[] = [
    {
        id: 1,
        category: '밤 문화 Talk',
        title: '오늘 퇴근길 노을 보셨나요? 진짜 힐링..✨',
        content: '요즘 일하느라 너무 바빴는데 잠깐 고개 들어보니 하늘이 너무 예쁘더라고요. 언니들도 오늘 하루 고생 많으셨어요!',
        author: '익명123',
        time: '10분 전',
        likes: 12,
        comments: 0,
        isHot: true,
    },
    {
        id: 17,
        category: '프리미엄 라운지',
        title: '멘탈 관리하는 나만의 루틴 공유 🧘‍♀️',
        content: '명상이랑 가벼운 독서가 큰 도움이 되네요. 바쁜 일상 속에서도 마음의 여유를 찾는 팁들입니다.',
        author: '퀸즈',
        time: '1시간 전',
        likes: 89,
        comments: 15,
    },
    {
        id: 6,
        category: '밤 문화 Talk',
        title: '동네 맛집 추천 좀 해주세요 (강남역 근처)',
        content: '오늘 친구랑 만나기로 했는데 조용하고 분위기 좋은 곳 있을까요? 파스타나 일식 선호합니다!',
        author: '배고픈다람쥐',
        time: '4시간 전',
        likes: 9,
        comments: 6,
    },
    {
        id: 18,
        category: '밤 문화 Talk',
        title: '멀티비타민 이거 진짜 물건이네요 ㅋㅋ',
        content: '직업 특성상 피로를 달고 사는데.. 이거 먹고 나서부터 아침이 달라요. 내돈내산 찐후기입니다.',
        author: '비타민짱',
        time: '45분 전',
        likes: 15,
        comments: 28,
    },
    {
        id: 19,
        category: '뷰티·패션·이벤트',
        title: '결혼식 하객룩 코디 투표 좀 해줘요! 👗',
        content: '1번 베이지 원피스 vs 2번 트위드 자켓+슬랙스. 주말에 친구 결혼식인데 뭐가 더 괜찮을까요?',
        author: '고민상담',
        time: '2시간 전',
        likes: 32,
        comments: 14,
    },
    {
        id: 20,
        category: '밤 문화 Talk',
        title: '반려견이랑 산책하기 좋은 코스 아시나요?',
        content: '저희 집 댕댕이가 너무 좋아하네요. 서울 근교에 강아지랑 가기 좋은 곳 추천 부탁드려요!',
        author: '댕댕맘',
        time: '3시간 전',
        likes: 18,
        comments: 5,
    },
    {
        id: 7,
        category: '밤 문화 Talk',
        title: '재테크 초보 탈출한 수기 올려봅니다',
        content: '일하면서 번 돈 어떻게 모을지 막막했는데.. 가계부 쓰기랑 적금부터 시작하니까 눈에 보이네요.',
        author: '저축왕',
        time: '5시간 전',
        likes: 45,
        comments: 18,
        isHot: true,
    },
    {
        id: 15,
        category: '무료법률상담',
        title: '임대차 계약 관련 상담 가능할까요?',
        content: '전세 사기 예방하고 싶은데 계약서 쓰기 전에 꼭 확인해야 할 것들 알려주세요 변호사님!',
        author: '이사갈래요',
        time: '13시간 전',
        likes: 15,
        comments: 8,
    },
    {
        id: 21,
        category: '밤 문화 Talk',
        title: '강남 쪽 오늘 손님 많나요? 분위기 어떤가요',
        content: '오늘 출근할지 말지 고민 중인데 현장 상황 아시는 분 계신가요? 어제는 좀 조용했어서 ㅠㅠ',
        author: '눈치게임',
        time: '30분 전',
        likes: 22,
        comments: 10,
    },
    {
        id: 22,
        category: '같이일할단짝',
        title: '부산 서면 2인조 짝꿍 구해요! 👯‍♀️',
        content: '마음 잘 맞고 예의 바른 언니 찾아요. 숙소 같이 쓰면서 으쌰으쌰 하실 분! 연락주세요.',
        author: '부산갈매기',
        time: '1시간 전',
        likes: 5,
        comments: 3,
    },
    {
        id: 23,
        category: '중고거래',
        title: '홀복 원피스 5벌 일괄 처분합니다 (55사이즈)',
        content: '스타일이 바뀌어서 싸게 내놔요. 상태 다 A급이고 드라이 완료했습니다. 쿨거시 네고 가능!',
        author: '미니멀라이프',
        time: '2시간 전',
        likes: 8,
        comments: 12,
    },
    {
        id: 24,
        category: '무료법률상담',
        title: '가게에서 정산금을 제때 안 주는데 어떻게 하죠?',
        content: '벌써 2주째 밀리고 있는데 사장님은 계속 기다리라고만 하네요.. 신고 가능한가요?',
        author: '답답이',
        time: '3시간 전',
        likes: 30,
        comments: 25,
        isHot: true,
    },
    {
        id: 25,
        category: '뷰티·패션·이벤트',
        title: '울쎄라 vs 슈링크 받아보신 분 후기 좀요!',
        content: '턱선 정리가 필요한데 뭐가 더 효과 좋을까요? 통증이랑 유지 기간 궁금해요.',
        author: '브이라인',
        time: '4시간 전',
        likes: 14,
        comments: 20,
    },
    {
        id: 26,
        category: '밤 문화 Talk',
        title: 'VIP 손님 관리 노하우 (feat. 매너팁 유도)',
        content: '진상 손님도 단골로 만드는 저만의 비법 공유합니다. 라운지 멤버들에게만 공개해요!',
        author: '프로페셔널',
        time: '5시간 전',
        likes: 156,
        comments: 42,
        isHot: true,
    },
    {
        id: 27,
        category: '밤 문화 Talk',
        title: '초보인데 주점 알바 꿀팁 있을까요?',
        content: '오늘 첫 출근인데 너무 떨려요.. 실수 안 하는 법, 손님 응대 팁 좀 알려주세요 선배님들!',
        author: '병아리',
        time: '6시간 전',
        likes: 28,
        comments: 31,
    },
    {
        id: 28,
        category: '같이일할단짝',
        title: '서울 논현동 룸메이트 구합니다 🏠',
        content: '깔끔하고 조용한 성격이신 분 환영해요. 보증금/월세 반반, 생활비 협의 가능합니다.',
        author: '독립만세',
        time: '7시간 전',
        likes: 11,
        comments: 4,
    },
    {
        id: 29,
        category: '중고거래',
        title: '다이슨 에어랩 컴플리트 롱 (거의 새거)',
        content: '선물 받았는데 똥손이라 잘 안 써서 팝니다.. 풀박이고 상태 최상이에요.',
        author: '고데기',
        time: '8시간 전',
        likes: 45,
        comments: 18,
    },
    {
        id: 30,
        category: '밤 문화 Talk',
        title: '다리 붓기 빼는 데는 역시 이게 최고네요',
        content: '압박스타킹이랑 L자 다리 20분씩 하니까 확실히 덜 부어요. 추천합니다!',
        author: '각선미',
        time: '9시간 전',
        likes: 67,
        comments: 9,
    },

    {
        id: 32,
        category: '밤 문화 Talk',
        title: '주말에 뭐 하고 보내시나요 다들?',
        content: '일 안 하는 날엔 집순이 모드인데.. 취미 생활 좀 가져볼까 해요. 추천해주세요!',
        author: '심심해',
        time: '하루 전',
        likes: 19,
        comments: 24,
    },
];

export const MOCK_COMMENTS = [
    { id: 101, postId: 1, author: '공감봇', content: '맞아요.. 오늘 노을 진짜 미쳤더라구요 ㅠㅠ', time: '5분 전' },
    { id: 102, postId: 1, author: '언니야', content: '고생 많으셨어요! 푹 쉬세요 ㅎㅎ', time: '2분 전' },
    { id: 103, postId: 7, author: '응원군', content: '수기 너무 잘 읽었습니다! 동기부여 되네요.', time: '1시간 전' },
    { id: 104, postId: 3, author: '메이크업러버', content: '정보 좀 알 수 있을까요? 쪽지 부탁드려요!', time: '30분 전' },
];
